### PR TITLE
Tests: Update tests to the recent changes in widgets API.

### LINKED ISSUE #221: CI is red - tests on Edge fail
`contentEditable="false"` attribute is not expected by the assertion but Edge sets it.

image

### LINKED ISSUE #5155: CI is red - tests on Edge fail
`contentEditable="false"` attribute is not expected by the assertion but Edge sets it.

image

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Tests: Update tests to the recent changes in widgets API. Closes ckeditor/ckeditor5#5155.

---

### Additional information

* Should be fixed now - using `env.isEdge` stubbing.

### CODE REVIEW

File: tests/image.js [hunk 1]
```diff
@@ -12,11 +12,17 @@ import { setData as setModelData } from '@ckeditor/ckeditor5-engine/src/dev-util
...
+import env from '@ckeditor/ckeditor5-utils/src/env';
 
 describe( 'Image', () => {
+	const initialEnvEdge = env.isEdge;
+
 	let editorElement, model, view, editor, document, viewDocument;
 
 	beforeEach( () => {
+		// Most tests assume non-edge environment but we do not set `contenteditable=false` on Edge so stub `env.isEdge`.
+		env.isEdge = false;
```
Comment (oskarwrobel) [inline tests/image.js]: You can use sinon for this
```js
sinon.stub( env, 'isEdge' ).get( () => true );
```
and restore the stub in `afterEach`
```js
env.isEdge.restore()
```
Or you can use sandbox from core test utils https://github.com/ckeditor/ckeditor5-core/blob/master/tests/_utils/utils.js#L26-L34

Comment (oskarwrobel) [reply tests/image.js]: But it's a detail.

**Comment by oskarwrobel** [comment]
1 lint issue
```
/home/travis/build/ckeditor/ckeditor5-image/tests/imageupload/imageuploadprogress.js
  24:8  error  Parsing error: Identifier 'env' has already been declared
✖ 1 problem (1 error, 0 warnings)
```
