### PR TITLE
T/77 Image captions in the view are hidden instead of being removed

### LINKED ISSUE #77: Yet another caption+undo bug: mapping empty caption.
**Steps to reproduce:**

1. Create image (must have empty caption).
2. Undo.

**Expected:** Image is removed.

**Actual:** Editor throws an error.

**Reason:**

To put things short and simple:

When model `<caption>` is empty, we remove `<figcaption>` element from view. But this causes a bug with undo:

1. When creating image, insert operation for caption is performed.
2. When undoing it, insert operation becomes remove operation for caption.
3. Remove operation has a range to remove, which is in `<figure>`.
4. However `<figcaption>` is not there, which throws an error (we are looking for a too big offset in `<figure>`).

It's easy to see that this is the problem, because you can undo the image insertion if you focus it.

**Solutions:**

There are two things we can do:

1. Introduce `remove:caption` converter which will check if the `<figcaption>` is there and consume change + stop event if it's not there.
2. Stop trying to fix all the issues that comes from the fact that we have element in model that sometimes is not in the view, and use CSS classes to hide it.

I am for 2.

### LINKED ISSUE #5080: Yet another caption+undo bug: mapping empty caption.
**Steps to reproduce:**

1. Create image (must have empty caption).
2. Undo.

**Expected:** Image is removed.

**Actual:** Editor throws an error.

**Reason:**

To put things short and simple:

When model `<caption>` is empty, we remove `<figcaption>` element from view. But this causes a bug with undo:

1. When creating image, insert operation for caption is performed.
2. When undoing it, insert operation becomes remove operation for caption.
3. Remove operation has a range to remove, which is in `<figure>`.
4. However `<figcaption>` is not there, which throws an error (we are looking for a too big offset in `<figure>`).

It's easy to see that this is the problem, because you can undo the image insertion if you focus it.

**Solutions:**

There are two things we can do:

1. Introduce `remove:caption` converter which will check if the `<figcaption>` is there and consume change + stop event if it's not there.
2. Stop trying to fix all the issues that comes from the fact that we have element in model that sometimes is not in the view, and use CSS classes to hide it.

I am for 2.

### PR DESCRIPTION
**Pull request by szymonkups**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Image captions in the view are hidden instead of being removed. Closes ckeditor/ckeditor5#5080 .

---

### Additional information

Please close #74 before.

### CODE REVIEW

File: src/imagecaption/imagecaptionengine.js [hunk 1]
```diff
@@ -77,102 +75,47 @@ export default class ImageCaptionEngine extends Plugin {
...
 
-		if ( selectedElement && isImageWidget( selectedElement ) ) {
-			const viewImage = viewCaptionElement.findAncestor( element => element == selectedElement );
-
-			if ( viewImage ) {
-				return;
-			}
+		// Hide last selected caption if have no child elements.
+		if ( this._lastSelectedCaption && !this._lastSelectedCaption.childCount ) {
+			this._lastSelectedCaption.addClass( 'ck-editable_hidden' );
```
Comment (oleq) [inline src/imagecaption/imagecaptionengine.js]: We have `.ck-hidden` class for this kind of things.

File: src/imagecaption/imagecaptionengine.js [hunk 2]
```diff
@@ -246,20 +169,16 @@ function captionModelToView( elementCreator ) {
 				elementCreator.clone( true ) :
 				elementCreator();
 
+			// Hide if empty.
+			if ( !captionElement.childCount ) {
+				viewCaption.addClass( 'ck-editable_hidden' );
```
Comment (oleq) [inline src/imagecaption/imagecaptionengine.js]: We have `.ck-hidden` class for this kind of things.

**Comment by Reinmar** [comment]
I asked @scofalik to check this PR.

File: src/imagecaption/imagecaptionengine.js [hunk 3]
```diff
@@ -201,42 +144,22 @@ function insertMissingModelCaptionElement( evt, changeType, data, batch ) {
...
 // @return {Function}
-function captionModelToView( elementCreator ) {
+function captionModelToView( elementCreator, hide = true ) {
 	return ( evt, data, consumable, conversionApi ) => {
 		const captionElement = data.item;
 
-		if ( isImage( captionElement.parent ) && ( captionElement.childCount > 0 ) ) {
+		// Return if element shouldn't be present when empty.
+		if ( !captionElement.childCount && !hide ) {
+			return;
```
Comment (scofalik) [inline src/imagecaption/imagecaptionengine.js:190]: I think it would be better if this part of code is in `if ( isImage( ... ) ) { ... }` so it won't ever affect other converters if we have different type of captions.

Comment (scofalik) [reply src/imagecaption/imagecaptionengine.js:190]: On the other hand it won't affect other converters because it does not consume anything, but I was also thinking whether the caption should not be consumed in this case 🤔 . Since we are not consuming, the code could stay here.

**Comment by scofalik** [comment]
I'd like to see one improvement introduced here (unless there is already ticket for this and you plan to work on it). Right now, when content is inserted into the caption, the caption does not show. The content could come from OT, for example.
